=== vseryakov/lmbox/lmbox.dtd
<!ELEMENT lmbox (system | template | page | object | include)*>
<!ELEMENT page ( line | vline | hline | rectangle | box | help | event | clocklabel | button | label | picture | listbox | filebrowser | webbrowser | scrollbar | textfield | togglebutton | timer | actionhandler)+>
<!ELEMENT include EMPTY>
<!ELEMENT template EMPTY>
<!ELEMENT button (#PCDATA|event)*>
<!ELEMENT picture EMPTY>
<!ELEMENT label (#PCDATA)>
<!ELEMENT clocklabel (#PCDATA)>
<!ELEMENT event (#PCDATA)>
<!ELEMENT scrollbar (event*)>
<!ELEMENT textfield (event*)>
<!ELEMENT togglebutton (#PCDATA|event)*>
<!ELEMENT system (event | timer | actionhandler)+>
<!ELEMENT timer (#PCDATA)>
<!ELEMENT object (event+)>
<!ELEMENT listbox (event*)>
<!ELEMENT filebrowser (event*)>
<!ELEMENT webbrowser (event*)>
<!ELEMENT actionhandler (#PCDATA)>
<!ELEMENT help (#PCDATA)>
<!ELEMENT line EMPTY>
<!ELEMENT vline EMPTY>
<!ELEMENT hline EMPTY>
<!ELEMENT box EMPTY>
<!ELEMENT rectangle EMPTY>

<!ATTLIST system
  xscale CDATA #IMPLIED
  yscale CDATA #IMPLIED
>

<!ATTLIST template
  name CDATA #REQUIRED
  action CDATA #IMPLIED
  autosize (true | false | 0 | 1) "false"
  enabled (true | false | 0 | 1) "true"
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  caption CDATA #IMPLIED
  captiondropx CDATA #IMPLIED
  captiondropy CDATA #IMPLIED
  captionx CDATA #IMPLIED
  captiony CDATA #IMPLIED
  checked (true | false | 0 | 1) "false"
  normalimage CDATA #IMPLIED
  normalfocusimage CDATA #IMPLIED
  checkedfocusimage CDATA #IMPLIED
  checkedimage CDATA #IMPLIED
  clockformat CDATA #IMPLIED
  font CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  fontdisabledcolor CDATA #IMPLIED
  fontfocusedcolor CDATA #IMPLIED
  fontpressedcolor CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  height CDATA #IMPLIED
  image CDATA #IMPLIED
  selitemborderx CDATA #IMPLIED
  selitembordery CDATA #IMPLIED
  itemborderx CDATA #IMPLIED
  itembordery CDATA #IMPLIED
  itemheight CDATA #IMPLIED
  knob CDATA #IMPLIED
  knobfocus CDATA #IMPLIED
  maximum CDATA #IMPLIED
  maxlength CDATA #IMPLIED
  minimum CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  pagestep CDATA #IMPLIED
  reversed CDATA #IMPLIED
  rootpath CDATA #IMPLIED
  scrollbar CDATA #IMPLIED
  scrollbarbackground CDATA #IMPLIED
  scrollbarbackgroundstyle (normal | tiled | fill | gradient | none) "normal"
  scrollbarknob CDATA #IMPLIED
  scrollbarwidth CDATA #IMPLIED
  selitembackground CDATA #IMPLIED
  selitembackgroundfocus CDATA #IMPLIED
  selitembackgroundcolor CDATA #IMPLIED
  selitembackgroundfocuscolor CDATA #IMPLIED
  selitembackgroundstyle (normal | tiled | fill | gradient | none) "normal"
  selitemfontcolor CDATA #IMPLIED
  selitemfontcolorfocus CDATA #IMPLIED
  textalign (left | right | center | top | bottom | topleft | topright | bottomleft | bottomright | vtop | vbottom | vcenter | hleft | hright | hcenter) "left"
  validchars CDATA #IMPLIED
  width CDATA #IMPLIED
  wordwrap (true | false | 0 | 1) "0"
  wrap (true | false | 0 | 1) "0"
  xscale CDATA #IMPLIED
  yscale CDATA #IMPLIED
>

<!ATTLIST include
  file CDATA #REQUIRED
>

<!ATTLIST object
  name CDATA #REQUIRED
>

<!ATTLIST page
  name ID #REQUIRED
  x CDATA #IMPLIED
  y CDATA #IMPLIED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  color CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  template CDATA #IMPLIED
>

<!ATTLIST line
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST vline
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST hline
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST box
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST rectangle
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST button
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  caption CDATA #IMPLIED
  captionx CDATA #IMPLIED
  captiony CDATA #IMPLIED
  captiondropx CDATA #IMPLIED
  captiondropy CDATA #IMPLIED
  template CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  fontfocusedcolor CDATA #IMPLIED
  fontdisabledcolor CDATA #IMPLIED
  fontpressedcolor CDATA #IMPLIED
  action CDATA #IMPLIED
  enabled (true | false | 0 | 1) "true"
  textalign (left | right | center | top | bottom) "center"
  autosize (true | false | 0 | 1) "false"
  wordwrap (true | false | 0 | 1) "false"
>

<!ATTLIST picture
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  image CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST label
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  caption CDATA #IMPLIED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  textalign (left | right | center | top | bottom | topleft | topright | bottomleft | bottomright | vtop | vbottom | vcenter | hleft | hright | hcenter) "left"
  autosize (true | false | 0 | 1) "false"
  wordwrap (true | false | 0 | 1) "false"
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
>

<!ATTLIST clocklabel
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  textalign (left | right | center | top | bottom) "left"
  autosize (true | false | 0 | 1) "false"
  wordwrap (true | false | 0 | 1) "false"
  clockformat CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
>

<!ATTLIST listbox
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  selitembackground CDATA #IMPLIED
  selitembackgroundfocus CDATA #IMPLIED
  selitembackgroundcolor CDATA #IMPLIED
  selitembackgroundfocuscolor CDATA #IMPLIED
  selitembackgroundstyle (normal | tiled) "normal"
  selitemfontcolor CDATA #IMPLIED
  selitemfontcolorfocus CDATA #IMPLIED
  scrollbar CDATA #IMPLIED
  scrollbarbackground CDATA #IMPLIED
  scrollbarbackgroundstyle (normal | tiled | gradient | none) "normal"
  scrollbarknob CDATA #IMPLIED
  scrollbarwidth CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
  selitemborderx CDATA #IMPLIED
  selitembordery CDATA #IMPLIED
  itemborderx CDATA #IMPLIED
  itembordery CDATA #IMPLIED
  itemheight CDATA #IMPLIED
  wrap (true | false | 0 | 1) "false"
>

<!ATTLIST filebrowser
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  selitembackground CDATA #IMPLIED
  selitembackgroundfocus CDATA #IMPLIED
  selitembackgroundstyle (normal | tiled | gradient | none) "normal"
  selitemfontcolor CDATA #IMPLIED
  selitemfontcolorfocus CDATA #IMPLIED
  scrollbar CDATA #IMPLIED
  scrollbarbackground CDATA #IMPLIED
  scrollbarbackgroundstyle (normal | tiled | gradient | none) "normal"
  scrollbarknob CDATA #IMPLIED
  scrollbarwidth CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
  selitemborderx CDATA #IMPLIED
  selitembordery CDATA #IMPLIED
  itemborderx CDATA #IMPLIED
  itembordery CDATA #IMPLIED
  itemheight CDATA #IMPLIED
  rootpath CDATA #IMPLIED
>

<!ATTLIST webbrowser
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  location CDATA #IMPLIED
>

<!ATTLIST scrollbar
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  template CDATA #IMPLIED
  knob CDATA #IMPLIED
  knobfocus CDATA #IMPLIED
  reversed CDATA #IMPLIED
  maximum CDATA #IMPLIED
  minimum CDATA #IMPLIED
  pagestep CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
>

<!ATTLIST textfield
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  maxlength CDATA #IMPLIED
  validchars CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  fontfocusedcolor CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  textalign CDATA #IMPLIED
  text CDATA #IMPLIED
>

<!ATTLIST togglebutton
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  normalimage CDATA #IMPLIED
  normalfocusimage CDATA #IMPLIED
  checkedimage CDATA #IMPLIED
  checkedfocusimage CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  action CDATA #IMPLIED
  enabled (true | false | 0 | 1) "true"
  checked (true | false | 0 | 1) "false"
>

<!ATTLIST event
  type CDATA #REQUIRED
>

<!ATTLIST timer
  name CDATA #IMPLIED
  interval CDATA #REQUIRED
  enabled (true | false | 0 | 1) "false"
>

<!ATTLIST actionhandler
  action CDATA #REQUIRED
>

=== vseryakov/lmbox/modules/music.xml
<?xml version="1.0"?>
<!DOCTYPE lmbox SYSTEM "lmbox.dtd">
<lmbox>

<system>
  <event name="mymusic">
    lmbox setpage musicpage
  </event>
</system>

<page name="musicpage" background="background.jpg">
  <help>
  Music player supports playback as single songs and the whole directories. Just
  select directory and press Play.

  Volume up/down will control music volume.

  Shuffle button when pressed will change it title to Unshuffle and when Play pressed 
  will randomize songs list.

  During playback, next page button will make the player to play next song in 
  the play list.
  </help>
  <event name="OnGotFocus">
    lmbox set musicfilelist rootpath [music_setup]
  </event>
  <event name="prevtrack"> music_prev </event>
  <clocklabel x="20" y="10" width="200" height="20" template="clocklabel"></clocklabel>
  <label name="musiccount" x="300" y="10" width="150" height="20" template="countlabel"></label>
  <label name="musictitle" x="400" y="10" template="titlelabel">lmBox: Music</label>
  <label name="musicinfo" x="285" y="40" width="290" height="320" template="t_musicinfo" />
  <picture name="musicicon" x="450" y="214" width="120" height="140" image="none.gif" />
  <filebrowser name="musicfilelist" x="20" y="40" width="250" height="320" template="t_musiclist">
    <event name="OnGotFocus">
      music_info count [lmbox get musicfilelist filename]
      music_info file [lmbox get musicfilelist filename]
    </event>
    <event name="OnPathChange">
      music_info count [lmbox get musicfilelist filename]
    </event>
    <event name="OnSelectionChange">
      music_info file [lmbox get musicfilelist filename]
    </event>
    <event name="OnChoose">
      music_play
    </event>
  </filebrowser>
  <button x="20" y="390" caption="Play" template="t_graybutton" action="play">
    <event name="OnGotFocus">
      lmbox set musicstatus caption "Play music track"
    </event>
    <event name="OnClick">
      music_play
    </event>
  </button>
  <button x="90" y="390" caption="Pause" template="t_graybutton" action="pause">
    <event name="OnGotFocus">
      lmbox set musicstatus caption "Pause music player"
    </event>
    <event name="OnClick">
      music_pause
    </event>
  </button>
  <button x="160" y="390" caption="Stop" template="t_graybutton" action="stop">
    <event name="OnGotFocus">
      lmbox set musicstatus caption "Stop music player"
    </event>
    <event name="OnClick">
      music_stop
    </event>
  </button>
  <button x="230" y="390" caption="Next" template="t_redbutton" action="red,nexttrack">
    <event name="OnGotFocus">
      lmbox set musicstatus caption "Play next track"
    </event>
    <event name="OnClick">
      music_next
    </event>
  </button>
  <button x="300" y="390" caption="Shuffle" template="t_greenbutton" action="green" name="shuffle">
    <event name="OnGotFocus">
      lmbox set musicstatus caption "Set/unset random playing mode"
    </event>
    <event name="OnClick">
      music_shuffle
    </event>
  </button>
  <button x="370" y="390" caption="Info" template="t_yellowbutton" action="yellow,info">
    <event name="OnGotFocus">
      lmbox set musicstatus caption "Scroll info text"
    </event>
    <event name="OnClick">
      music_info scroll [lmbox get musicfilelist filename]
    </event>
  </button>
  <button x="440" y="390" caption="Favorite" template="t_bluebutton" action="blue">
    <event name="OnGotFocus">
      lmbox set status caption "Add song(s) to favorite links"
    </event>
    <event name="OnClick">
      music_favorite [lmbox get musicfilelist filename]
    </event>
  </button>
  <button x="520" y="390" caption="Back" template="t_graybutton" action="cancel">
    <event name="OnGotFocus">
      lmbox set musicstatus caption "Go to main menu"
    </event>
    <event name="OnClick">
      lmbox setpage mainpage
    </event>
  </button>
  <label name="status" x="20" y="425" width="620" height="30" template="statuslabel"></label>
</page>

<page name="musicselectpage" background="background.jpg">
  <event name="OnGotFocus">
    lmbox set musicfilelist rootpath [music_setup]
    music_info count [lmbox get musicfilelist filename]
  </event>
  <clocklabel x="20" y="10" width="200" height="20" template="clocklabel"></clocklabel>
  <label name="musiccount" x="300" y="10" width="150" height="20" template="countlabel"></label>
  <label name="musictitle" x="500" y="10" template="titlelabel">lmBox: Music</label>
  <filebrowser name="musicfilelist" x="15" y="50" width="570" height="320" template="t_listbox2">
    <event name="OnChoose">
      music_select
    </event>
    <event name="OnPathChange">
      music_info count [lmbox get musicfilelist filename]
    </event>
  </filebrowser>
  <button x="20" y="390" caption="Select" template="t_redbutton" action="play">
    music_select
  </button>
  <button x="150" y="390" caption="Cancel" template="t_bluebutton" action="cancel">
    lmbox setpage [lmbox prevpage]
  </button>
  <label name="status" x="15" y="420" width="620" height="30" template="statuslabel"></label>
</page>

</lmbox>

=== vseryakov/lmbox/modules/live365.xml
<?xml version="1.0"?>
<!DOCTYPE lmbox SYSTEM "lmbox.dtd">
<lmbox>

<page name="live365page" background="background.jpg">
   <event name="OnGotFocus">
     live365_setup
   </event>
   
   <event name="stop"> live365_stop </event>
   <event name="pause"> live365_pause </event>
   <event name="cancel"> lmbox setpage mainpage </event>
   <event name="play"> live365_play [lmbox get live365stationlist selecteddata] </event>
   
   <clocklabel x="20" y="10"  width="300" height="20" template="clocklabel"></clocklabel>
   <label x="400" y="10" template="titlelabel">lmBox: Live365.com Radio</label>
   <listbox name="live365genrelist" x="15" y="50" width="200" height="200" template="t_live365list">
     <event name="OnChoose">
       lmbox call live365stationlist setfocus
     </event>
     <event name="OnGotFocus">
       live365_info stations [lmbox get live365genrelist selecteddata]
       lmbox set status caption "Live365.com music genres"
     </event>
     <event name="OnSelectionChange">
       live365_info stations [lmbox get live365genrelist selecteddata]
     </event>
   </listbox>
   <listbox name="live365stationlist" x="225" y="50" width="330" height="200" template="t_live365list" fontcolor="#e0e2e5">
     <event name="OnChoose">
       live365_play [lmbox get live365stationlist selecteddata]
     </event>
     <event name="OnGotFocus">
       live365_info info [lmbox get live365stationlist selecteddata]
       lmbox set status caption "Live365.com stations for selected genre"
     </event>
     <event name="OnSelectionChange">
       live365_info info [lmbox get live365stationlist selecteddata]
     </event>
   </listbox>
   <label name="live365info" x="15" y="260" width="400" height="130" template="t_live365info" ></label>
   <picture name="live365icon" x="420" y="265" width="135" height="80" image="images/menu/live365.jpg" />
   <button x="420" y="350" caption="Relogin" template="t_bluebutton" width="50" fontsize="10" action="blue" >
     <event name="OnGotFocus">
       lmbox set status caption "Login into live365.com if session already expired"
     </event>
     <event name="OnClick">
       live365_login 1
     </event>
   </button>
   <button x="475" y="350" caption="Refresh" template="t_yellowbutton" width="50" fontsize="9" action="yellow" >
     <event name="OnGotFocus">
       lmbox set status caption "Refresh live365.com database"
     </event>
     <event name="OnClick">
       lmbox run "live365_load 1;live365_setup"
     </event>
   </button>
   <button x="530" y="350" caption="Favorite" template="t_greenbutton" width="50" fontsize="9" action="green" >
     <event name="OnGotFocus">
       lmbox set status caption "Add station to favorite links"
     </event>
     <event name="OnClick">
       live365_favorite [lmbox get live365stationlist selecteddata]
     </event>
   </button>
   <label name="status" x="10" y="400" width="620" height="40" template="statuslabel"></label>
</page>

<page name="live365configpage" background="background.jpg">
  <clocklabel x="20" y="10" width="200" height="20" template="clocklabel" />
  <label x="400" y="10" template="titlelabel">lmBox: Live365.com Settings</label>

  <label x="30" y="70" width="100" height="20" template="infolabel">Username:</label>
  <textfield name="live365_user" x="200" y="65" width="140" template="t_textfield">
    <event name="OnGotFocus">
      lmbox set status caption "Username of live365.com account"
    </event>
  </textfield>
  <label x="30" y="100" width="100" height="20" template="infolabel">Password:</label>
  <textfield name="live365_passwd" x="200" y="95" width="140" template="t_textfield">
    <event name="OnGotFocus">
      lmbox set status caption "Password for live365.com account"
    </event>
  </textfield>

  <button x="100" y="370" caption="Save" template="t_button2" action="save">
    config_save
    lmbox setpage configpage
  </button>
  <button x="200" y="370" caption="Login" template="t_button2">
    config_save
    if { [live365_login 1] == -1 } {
      lmbox set status caption "Unable to login to Live365.com account"
    } else {
      lmbox set status caption "Logged in successfully into live365.com"
    }
  </button>
  <button x="300" y="370" caption="Reload" template="t_button2">
    live365_load 1
    lmbox set status caption "live365.com directory has been reloaded"
  </button>
  <button x="400" y="370" caption="Back" template="t_button2" action="cancel">
    lmbox setpage configpage
  </button>
  <label name="status" x="10" y="408" width="480" height="50" template="statuslabel"></label>
</page>

</lmbox>
