=== vseryakov/lmbox/lmbox.dtd
<!ELEMENT lmbox (system | template | page | object | include)*>
<!ELEMENT page ( line | vline | hline | rectangle | box | help | event | clocklabel | button | label | picture | listbox | filebrowser | webbrowser | scrollbar | textfield | togglebutton | timer | actionhandler)+>
<!ELEMENT include EMPTY>
<!ELEMENT template EMPTY>
<!ELEMENT button (#PCDATA|event)*>
<!ELEMENT picture EMPTY>
<!ELEMENT label (#PCDATA)>
<!ELEMENT clocklabel (#PCDATA)>
<!ELEMENT event (#PCDATA)>
<!ELEMENT scrollbar (event*)>
<!ELEMENT textfield (event*)>
<!ELEMENT togglebutton (#PCDATA|event)*>
<!ELEMENT system (event | timer | actionhandler)+>
<!ELEMENT timer (#PCDATA)>
<!ELEMENT object (event+)>
<!ELEMENT listbox (event*)>
<!ELEMENT filebrowser (event*)>
<!ELEMENT webbrowser (event*)>
<!ELEMENT actionhandler (#PCDATA)>
<!ELEMENT help (#PCDATA)>
<!ELEMENT line EMPTY>
<!ELEMENT vline EMPTY>
<!ELEMENT hline EMPTY>
<!ELEMENT box EMPTY>
<!ELEMENT rectangle EMPTY>

<!ATTLIST system
  xscale CDATA #IMPLIED
  yscale CDATA #IMPLIED
>

<!ATTLIST template
  name CDATA #REQUIRED
  action CDATA #IMPLIED
  autosize (true | false | 0 | 1) "false"
  enabled (true | false | 0 | 1) "true"
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  caption CDATA #IMPLIED
  captiondropx CDATA #IMPLIED
  captiondropy CDATA #IMPLIED
  captionx CDATA #IMPLIED
  captiony CDATA #IMPLIED
  checked (true | false | 0 | 1) "false"
  normalimage CDATA #IMPLIED
  normalfocusimage CDATA #IMPLIED
  checkedfocusimage CDATA #IMPLIED
  checkedimage CDATA #IMPLIED
  clockformat CDATA #IMPLIED
  font CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  fontdisabledcolor CDATA #IMPLIED
  fontfocusedcolor CDATA #IMPLIED
  fontpressedcolor CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  height CDATA #IMPLIED
  image CDATA #IMPLIED
  selitemborderx CDATA #IMPLIED
  selitembordery CDATA #IMPLIED
  itemborderx CDATA #IMPLIED
  itembordery CDATA #IMPLIED
  itemheight CDATA #IMPLIED
  knob CDATA #IMPLIED
  knobfocus CDATA #IMPLIED
  maximum CDATA #IMPLIED
  maxlength CDATA #IMPLIED
  minimum CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  pagestep CDATA #IMPLIED
  reversed CDATA #IMPLIED
  rootpath CDATA #IMPLIED
  scrollbar CDATA #IMPLIED
  scrollbarbackground CDATA #IMPLIED
  scrollbarbackgroundstyle (normal | tiled | fill | gradient | none) "normal"
  scrollbarknob CDATA #IMPLIED
  scrollbarwidth CDATA #IMPLIED
  selitembackground CDATA #IMPLIED
  selitembackgroundfocus CDATA #IMPLIED
  selitembackgroundcolor CDATA #IMPLIED
  selitembackgroundfocuscolor CDATA #IMPLIED
  selitembackgroundstyle (normal | tiled | fill | gradient | none) "normal"
  selitemfontcolor CDATA #IMPLIED
  selitemfontcolorfocus CDATA #IMPLIED
  textalign (left | right | center | top | bottom | topleft | topright | bottomleft | bottomright | vtop | vbottom | vcenter | hleft | hright | hcenter) "left"
  validchars CDATA #IMPLIED
  width CDATA #IMPLIED
  wordwrap (true | false | 0 | 1) "0"
  wrap (true | false | 0 | 1) "0"
  xscale CDATA #IMPLIED
  yscale CDATA #IMPLIED
>

<!ATTLIST include
  file CDATA #REQUIRED
>

<!ATTLIST object
  name CDATA #REQUIRED
>

<!ATTLIST page
  name ID #REQUIRED
  x CDATA #IMPLIED
  y CDATA #IMPLIED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  color CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  template CDATA #IMPLIED
>

<!ATTLIST line
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST vline
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST hline
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST box
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST rectangle
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST button
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  caption CDATA #IMPLIED
  captionx CDATA #IMPLIED
  captiony CDATA #IMPLIED
  captiondropx CDATA #IMPLIED
  captiondropy CDATA #IMPLIED
  template CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  fontfocusedcolor CDATA #IMPLIED
  fontdisabledcolor CDATA #IMPLIED
  fontpressedcolor CDATA #IMPLIED
  action CDATA #IMPLIED
  enabled (true | false | 0 | 1) "true"
  textalign (left | right | center | top | bottom) "center"
  autosize (true | false | 0 | 1) "false"
  wordwrap (true | false | 0 | 1) "false"
>

<!ATTLIST picture
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  image CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST label
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  caption CDATA #IMPLIED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  textalign (left | right | center | top | bottom | topleft | topright | bottomleft | bottomright | vtop | vbottom | vcenter | hleft | hright | hcenter) "left"
  autosize (true | false | 0 | 1) "false"
  wordwrap (true | false | 0 | 1) "false"
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
>

<!ATTLIST clocklabel
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  textalign (left | right | center | top | bottom) "left"
  autosize (true | false | 0 | 1) "false"
  wordwrap (true | false | 0 | 1) "false"
  clockformat CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
>

<!ATTLIST listbox
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  selitembackground CDATA #IMPLIED
  selitembackgroundfocus CDATA #IMPLIED
  selitembackgroundcolor CDATA #IMPLIED
  selitembackgroundfocuscolor CDATA #IMPLIED
  selitembackgroundstyle (normal | tiled) "normal"
  selitemfontcolor CDATA #IMPLIED
  selitemfontcolorfocus CDATA #IMPLIED
  scrollbar CDATA #IMPLIED
  scrollbarbackground CDATA #IMPLIED
  scrollbarbackgroundstyle (normal | tiled | gradient | none) "normal"
  scrollbarknob CDATA #IMPLIED
  scrollbarwidth CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
  selitemborderx CDATA #IMPLIED
  selitembordery CDATA #IMPLIED
  itemborderx CDATA #IMPLIED
  itembordery CDATA #IMPLIED
  itemheight CDATA #IMPLIED
  wrap (true | false | 0 | 1) "false"
>

<!ATTLIST filebrowser
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  selitembackground CDATA #IMPLIED
  selitembackgroundfocus CDATA #IMPLIED
  selitembackgroundstyle (normal | tiled | gradient | none) "normal"
  selitemfontcolor CDATA #IMPLIED
  selitemfontcolorfocus CDATA #IMPLIED
  scrollbar CDATA #IMPLIED
  scrollbarbackground CDATA #IMPLIED
  scrollbarbackgroundstyle (normal | tiled | gradient | none) "normal"
  scrollbarknob CDATA #IMPLIED
  scrollbarwidth CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
  selitemborderx CDATA #IMPLIED
  selitembordery CDATA #IMPLIED
  itemborderx CDATA #IMPLIED
  itembordery CDATA #IMPLIED
  itemheight CDATA #IMPLIED
  rootpath CDATA #IMPLIED
>

<!ATTLIST webbrowser
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  location CDATA #IMPLIED
>

<!ATTLIST scrollbar
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  template CDATA #IMPLIED
  knob CDATA #IMPLIED
  knobfocus CDATA #IMPLIED
  reversed CDATA #IMPLIED
  maximum CDATA #IMPLIED
  minimum CDATA #IMPLIED
  pagestep CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
>

<!ATTLIST textfield
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  maxlength CDATA #IMPLIED
  validchars CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  fontfocusedcolor CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  textalign CDATA #IMPLIED
  text CDATA #IMPLIED
>

<!ATTLIST togglebutton
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  normalimage CDATA #IMPLIED
  normalfocusimage CDATA #IMPLIED
  checkedimage CDATA #IMPLIED
  checkedfocusimage CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  action CDATA #IMPLIED
  enabled (true | false | 0 | 1) "true"
  checked (true | false | 0 | 1) "false"
>

<!ATTLIST event
  type CDATA #REQUIRED
>

<!ATTLIST timer
  name CDATA #IMPLIED
  interval CDATA #REQUIRED
  enabled (true | false | 0 | 1) "false"
>

<!ATTLIST actionhandler
  action CDATA #REQUIRED
>

=== vseryakov/lmbox/modules/favorites.xml
<?xml version="1.0"?>
<!DOCTYPE lmbox SYSTEM "lmbox.dtd">
<lmbox>

<page name="favorites_page" background="background.jpg">
  <event name="OnGotFocus">
    favorites_setup
    lmbox call favorites_list setfocus
    favorites_info info [lmbox get favorites_list selecteddata]
  </event>
  <clocklabel x="20" y="10" width="300" height="20" template="clocklabel"></clocklabel>
  <label x="450" y="10" template="titlelabel">lmBox: Favorites</label>
  <listbox name="favorites_list" x="15" y="40" width="400" height="290" template="t_favoriteslist">
    <event name="OnChoose">
      favorites_play [lmbox get favorites_list selecteddata]
    </event>
    <event name="OnSelectionChange,OnGotFocus">
      favorites_info info [lmbox get favorites_list selecteddata]
    </event>
  </listbox>
  <picture name="favorites_image" x="450" y="40" width="160" height="180" image="none.gif" />
  <button x="20" y="340" caption="Play" template="t_graybutton" action="play">
    <event name="OnGotFocus">
      lmbox set status caption "Choose favorite link"
    </event>
    <event name="OnClick">
      lmbox run "favorites_play [lmbox get favorites_list selecteddata]"
    </event>
  </button>
  <button x="80" y="340" caption="New" template="t_bluebutton" action="blue" >
    <event name="OnGotFocus">
      lmbox set status caption "Add new favorite link"
    </event>
    <event name="OnClick">
      favorites_edit ""
    </event>
  </button>
  <button x="140" y="340" caption="Back" template="t_graybutton" action="cancel">
    <event name="OnGotFocus">
      lmbox set status caption "Go to main menu"
    </event>
    <event name="OnClick">
      lmbox setpage mainpage
    </event>
  </button>
  <button name="favorites_details" x="200" y="340" caption="Details" template="t_greenbutton" action="green,info">
    <event name="OnGotFocus">
      lmbox set status caption "Update/Delete favorite link from the list"
    </event>
    <event name="OnClick">
      favorites_edit [lmbox get favorites_list selecteddata]
    </event>
  </button>
  <button name="favorites_move" x="260" y="340" caption="Favorite" template="t_graybutton">
    <event name="OnGotFocus">
      lmbox set status caption "Move this link to favorites list"
    </event>
    <event name="OnClick">
      favorites_move [lmbox get favorites_list selecteddata]
    </event>
  </button>
  <label name="status" x="50" y="380" width="550" height="80" template="statuslabel" />
</page>

<page name="favorites_editpage" background="background.jpg">
  <clocklabel x="20" y="10" width="300" height="20" template="clocklabel"></clocklabel>
  <label x="400" y="10" template="titlelabel">lmBox: New Favorite Link</label>
  <rectangle x="40" y="40" width="400" height="290" color="#e0e2e5" borderstyle="round" />
  <label x="50" y="60" width="100" height="20" template="infolabel">Type:</label>
  <listbox name="favorites_type" x="180" y="55" width="240" height="20" template="t_listbox5" selitemfontcolor="#000000" >
    <event name="OnGotFocus">
      lmbox set status caption "Type of the favorite link, for Web links or Flash videos use Web type"
    </event>
  </listbox>
  <label x="50" y="100" width="100" height="20" template="infolabel">Title:</label>
  <textfield name="favorites_title" x="180" y="95" width="240" template="t_textfield">
    <event name="OnGotFocus">
      lmbox set status caption "Name of the favorite link"
    </event>
  </textfield>
  <label x="50" y="140" width="100" height="20" template="infolabel">URL:</label>
  <textfield name="favorites_url" x="180" y="135" width="240" template="t_textfield">
    <event name="OnGotFocus">
      lmbox set status caption "Url of the favorite link"
    </event>
  </textfield>
  <label x="50" y="180" width="100" height="20" template="infolabel">Description:</label>
  <textfield name="favorites_description" x="180" y="175" width="240" template="t_textfield">
    <event name="OnGotFocus">
      lmbox set status caption "Description of the favorite link"
    </event>
  </textfield>
  <label x="50" y="220" width="100" height="20" template="infolabel">Category:</label>
  <label name="favorites_class" x="180" y="215" width="240" height="20" template="infolabel" />
  <label x="50" y="260" width="100" height="20" template="infolabel">Expires:</label>
  <listbox name="favorites_expires" x="180" y="255" width="240" height="20" template="t_listbox5" selitemfontcolor="#000000" >
    <event name="OnGotFocus">
      lmbox set status caption "When this link will expire"
    </event>
  </listbox>
  <label name="favorites_expires2" x="180" y="290" width="240" height="20" template="infolabel"/>
  <picture name="favorites_icon" x="450" y="40" width="160" height="180" image="none.gif" />
  <button x="20" y="350" caption="Save" template="t_redbutton" action="red">
    <event name="OnGotFocus">
      lmbox set status caption "Save favorites info"
    </event>
    <event name="OnClick">
      favorites_save [lmbox get favorites_editpage data]
    </event>
  </button>
  <button x="80" y="350" caption="Delete" template="t_bluebutton" action="blue">
    <event name="OnGotFocus">
      lmbox set status caption "Delete favorite link from the list"
    </event>
    <event name="OnClick">
      favorites_delete [lmbox get favorites_editpage data]
    </event>
  </button>
  <button x="140" y="350" caption="Back" template="t_graybutton" action="cancel">
    <event name="OnGotFocus">
      lmbox set status caption "Return to the list"
    </event>
    <event name="OnClick">
      lmbox setpage favorites_mosaicpage
    </event>
  </button>
  <label name="status" x="50" y="390" width="550" height="60" template="statuslabel" />
</page>

<page name="favorites_mosaicpage" background="background.jpg" >
  <event name="OnGotFocus">
    lmbox_mosaic favorites init favorites_filter -refresh
  </event>
  <event name="stop">
    player_stop
  </event>

  <clocklabel x="20" y="10" width="300" height="20" template="clocklabel"></clocklabel>

  <label name="favorites_count" x="350" y="10" width="200" height="20" template="countlabel"></label>

  <label x="450" y="10" template="titlelabel">lmBox: Favorites</label>

  <line x="13" y="27" width="600" height="1" template="titlelabel" />

  <scrollbar name="favorites_scroll" x="570" y="40" width="15" height="320" contenty="23"
             background="scrollbarvv.png"
             knob="knobv.png"
             knbofocus="knobv.png"
             backgroundstyle="scaled">
    <event name="OnChange">
      lmbox_mosaic favorites update [lmbox get favorites_scroll value]
    </event>
  </scrollbar>

  <picture name="favorites_00" x="50" y="40" template="t_movieicon" />
  <picture name="favorites_01" x="180" y="40" template="t_movieicon" />
  <picture name="favorites_02" x="310" y="40" template="t_movieicon" />
  <picture name="favorites_03" x="440" y="40" template="t_movieicon" />
  <label name="label_00" x="50" y="185" template="t_movielabel" />
  <label name="label_01" x="180" y="185" template="t_movielabel" />
  <label name="label_02" x="310" y="185" template="t_movielabel" />
  <label name="label_03" x="440" y="185" template="t_movielabel" />

  <picture name="favorites_10" x="50" y="210" template="t_movieicon" />
  <picture name="favorites_11" x="180" y="210"  template="t_movieicon" />
  <picture name="favorites_12" x="310" y="210" template="t_movieicon" />
  <picture name="favorites_13" x="440" y="210" template="t_movieicon" />
  <label name="label_10" x="50" y="355" template="t_movielabel" />
  <label name="label_11" x="180" y="355" template="t_movielabel" />
  <label name="label_12" x="310" y="355" template="t_movielabel" />
  <label name="label_13" x="440" y="355" template="t_movielabel" />

  <button x="50" y="380" caption="Play" template="t_graybutton" action="play">
    <event name="OnGotFocus">
      lmbox set status caption "Choose favorite link"
    </event>
    <event name="OnClick">
      favorites_play [lmbox var favorites_id]
    </event>
  </button>

  <button x="110" y="380" caption="New" template="t_bluebutton" action="blue" >
    <event name="OnGotFocus">
      lmbox set status caption "Add new favorite link"
    </event>
    <event name="OnClick">
      favorites_edit ""
    </event>
  </button>

  <button x="170" y="380" caption="Back" template="t_graybutton" action="cancel">
    <event name="OnGotFocus">
      lmbox set status caption "Go to main menu"
    </event>
    <event name="OnClick">
      lmbox setpage mainpage
    </event>
  </button>

  <button name="favorites_details" x="230" y="380" caption="Details" template="t_greenbutton" action="green,info">
    <event name="OnGotFocus">
      lmbox set status caption "Update/Delete favorite link from the list"
    </event>
    <event name="OnClick">
      favorites_edit [lmbox var favorites_id]
    </event>
  </button>

  <textfield name="favorites_filter" x="290" y="380" template="t_moviefilter" />

  <button name="favorites_move" x="350" y="380" caption="Favorite" template="t_graybutton">
    <event name="OnGotFocus">
      lmbox set status caption "Move this link to favorites list"
    </event>
    <event name="OnClick">
      favorites_move [lmbox var favorites_id]
      lmbox_mosaic favorites update
    </event>
  </button>

  <label name="status" x="50" y="405" width="550" height="30" template="statuslabel" />

</page>

</lmbox>

=== vseryakov/lmbox/modules/photo.xml
<?xml version="1.0"?>
<!DOCTYPE lmbox SYSTEM "lmbox.dtd">
<lmbox>

<system>
  <event name="mypictures">
    lmbox setpage photopage
  </event>
</system>
   
<page name="photopage" background="background.jpg">
   <help>
   To autoplay the whole directory select it and press Play.
   To rotate the image, use volume up/down buttons.
   </help>
   <event name="volumeup">
     lmbox call photoimage rotateimage -90
   </event>
   <event name="volumedown">
     lmbox call photoimage rotateimage 90
   </event>
   <event name="play">
     lmbox set phototimer enabled 1
     photo_play [lmbox get photofilelist filename]
   </event>
   <event name="stop">
     lmbox set phototimer enabled 0
     photo_stop
   </event>
   <timer name="phototimer" interval="5000" enabled="false">
     photo_play
   </timer>
   <event name="OnGotFocus">
     lmbox set photofilelist rootpath [photo_setup]
   </event>
   <label name="photostatus" x="20" y="10" width="300" height="20" template="yellowlabel"></label>
   <label name="photocount" x="400" y="10" width="150" height="20" template="countlabel"></label>
   <label name="phototitle" x="500" y="10" template="titlelabel">lmBox: Photos</label>
   <filebrowser name="photofilelist" x="10" y="40" width="130" height="370" template="t_photolist">
     <event name="OnSelectionChange">
       photo_show [lmbox get photofilelist filename]
     </event>
     <event name="OnChoose">
       photo_stop
       photo_show [lmbox get photofilelist filename]
     </event>
     <event name="OnPathChange">
       photo_show [lmbox get photofilelist filename]
     </event>
   </filebrowser>
   <picture name="photoimage" x="145" y="40" width="475" height="405" image="none.gif" borderstyle="normal" bordercolor="#FFFFFF" />
   <button x="20" y="415" caption="Back" template="t_button2" action="cancel">
      photo_exit
   </button>
</page>

</lmbox>

=== vseryakov/lmbox/modules/stock.xml
<?xml version="1.0"?>
<!DOCTYPE lmbox SYSTEM "lmbox.dtd">
<lmbox>

<page name="stockpage" background="background.jpg" >
  <event name="OnGotFocus">
    stock_setup
    lmbox call stocklist setfocus
    lmbox set stocksymbol text Symbol
  </event>
  <clocklabel x="20" y="10" width="300" height="20" template="clocklabel" />
  <label x="450" y="10" template="titlelabel">lmBox: Stocks</label>
  <listbox name="stocklist" x="15" y="40" width="300" height="295" template="t_stocklist" >
    <event name="OnGotFocus">
      stock_info [lmbox get stocklist selecteddata]
    </event>
    <event name="OnSelectionChange">
      stock_info [lmbox get stocklist selecteddata]
    </event>
  </listbox>
  <label name="stockinfo" x="340" y="40" width="270" height="180" borderstyle="round" contentx="5" contenty="5" wordwrap="true" fontcolor="#000000" font="vera.ttf" fontsize="13" />
  <rectangle name="stockchart" x="340" y="222" width="270" height="100" borderstyle="round" color="#0000FF" />
  <button x="20" y="340" caption="Refresh" template="t_redbutton" action="red">
    <event name="OnGotFocus">
      lmbox set status caption "Refresh quotes"
    </event>
    <event name="OnClick">
      stock_schedule
      stock_setup
      stock_info [lmbox get stocklist selecteddata]
    </event>
  </button>
  <button x="80" y="340" caption="Scale+" template="t_greenbutton" action="green">
    <event name="OnGotFocus">
      lmbox set status caption "See symbol details"
    </event>
    <event name="OnClick">
      stock_info [lmbox get stocklist selecteddata] 1
    </event>
  </button>
  <button x="140" y="340" caption="Scale-" template="t_bluebutton" action="blue">
    <event name="OnGotFocus">
      lmbox set status caption "See symbol details"
    </event>
    <event name="OnClick">
      stock_info [lmbox get stocklist selecteddata] -1
    </event>
  </button>
  <button x="200" y="340" caption="Back" template="t_graybutton" action="cancel">
    <event name="OnGotFocus">
      lmbox set status caption "Go to main menu"
    </event>
    <event name="OnClick">
      lmbox setpage mainpage
    </event>
  </button>
  <button x="260" y="340" caption="Delete" template="t_graybutton">
    <event name="OnGotFocus">
      lmbox set status caption "Delete quote from the list"
    </event>
    <event name="OnClick">
      stock_delete [lmbox get stocklist selecteddata]
    </event>
  </button>
  <textfield name="stocksymbol" x="320" y="340" template="t_yellowbutton" fontcolor="#e0e2e5" >
    <event name="OnGotFocus">
      lmbox set status caption "Enter symbol"
      if { [lmbox get stocksymbol text] == "Symbol" } {
        lmbox set stocksymbol text ""
      }
    </event>
    <event name="OnLostFocus">
      if { [set text [lmbox get stocksymbol text]] != "" } {
        stock_add $text
      }
      lmbox set stocksymbol text Symbol
    </event>
  </textfield>
  <label name="status" x="15" y="400" width="600" height="40" template="statuslabel" />
</page>

</lmbox>
