=== vseryakov/lmbox/lmbox.dtd
<!ELEMENT lmbox (system | template | page | object | include)*>
<!ELEMENT page ( line | vline | hline | rectangle | box | help | event | clocklabel | button | label | picture | listbox | filebrowser | webbrowser | scrollbar | textfield | togglebutton | timer | actionhandler)+>
<!ELEMENT include EMPTY>
<!ELEMENT template EMPTY>
<!ELEMENT button (#PCDATA|event)*>
<!ELEMENT picture EMPTY>
<!ELEMENT label (#PCDATA)>
<!ELEMENT clocklabel (#PCDATA)>
<!ELEMENT event (#PCDATA)>
<!ELEMENT scrollbar (event*)>
<!ELEMENT textfield (event*)>
<!ELEMENT togglebutton (#PCDATA|event)*>
<!ELEMENT system (event | timer | actionhandler)+>
<!ELEMENT timer (#PCDATA)>
<!ELEMENT object (event+)>
<!ELEMENT listbox (event*)>
<!ELEMENT filebrowser (event*)>
<!ELEMENT webbrowser (event*)>
<!ELEMENT actionhandler (#PCDATA)>
<!ELEMENT help (#PCDATA)>
<!ELEMENT line EMPTY>
<!ELEMENT vline EMPTY>
<!ELEMENT hline EMPTY>
<!ELEMENT box EMPTY>
<!ELEMENT rectangle EMPTY>

<!ATTLIST system
  xscale CDATA #IMPLIED
  yscale CDATA #IMPLIED
>

<!ATTLIST template
  name CDATA #REQUIRED
  action CDATA #IMPLIED
  autosize (true | false | 0 | 1) "false"
  enabled (true | false | 0 | 1) "true"
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  caption CDATA #IMPLIED
  captiondropx CDATA #IMPLIED
  captiondropy CDATA #IMPLIED
  captionx CDATA #IMPLIED
  captiony CDATA #IMPLIED
  checked (true | false | 0 | 1) "false"
  normalimage CDATA #IMPLIED
  normalfocusimage CDATA #IMPLIED
  checkedfocusimage CDATA #IMPLIED
  checkedimage CDATA #IMPLIED
  clockformat CDATA #IMPLIED
  font CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  fontdisabledcolor CDATA #IMPLIED
  fontfocusedcolor CDATA #IMPLIED
  fontpressedcolor CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  height CDATA #IMPLIED
  image CDATA #IMPLIED
  selitemborderx CDATA #IMPLIED
  selitembordery CDATA #IMPLIED
  itemborderx CDATA #IMPLIED
  itembordery CDATA #IMPLIED
  itemheight CDATA #IMPLIED
  knob CDATA #IMPLIED
  knobfocus CDATA #IMPLIED
  maximum CDATA #IMPLIED
  maxlength CDATA #IMPLIED
  minimum CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  pagestep CDATA #IMPLIED
  reversed CDATA #IMPLIED
  rootpath CDATA #IMPLIED
  scrollbar CDATA #IMPLIED
  scrollbarbackground CDATA #IMPLIED
  scrollbarbackgroundstyle (normal | tiled | fill | gradient | none) "normal"
  scrollbarknob CDATA #IMPLIED
  scrollbarwidth CDATA #IMPLIED
  selitembackground CDATA #IMPLIED
  selitembackgroundfocus CDATA #IMPLIED
  selitembackgroundcolor CDATA #IMPLIED
  selitembackgroundfocuscolor CDATA #IMPLIED
  selitembackgroundstyle (normal | tiled | fill | gradient | none) "normal"
  selitemfontcolor CDATA #IMPLIED
  selitemfontcolorfocus CDATA #IMPLIED
  textalign (left | right | center | top | bottom | topleft | topright | bottomleft | bottomright | vtop | vbottom | vcenter | hleft | hright | hcenter) "left"
  validchars CDATA #IMPLIED
  width CDATA #IMPLIED
  wordwrap (true | false | 0 | 1) "0"
  wrap (true | false | 0 | 1) "0"
  xscale CDATA #IMPLIED
  yscale CDATA #IMPLIED
>

<!ATTLIST include
  file CDATA #REQUIRED
>

<!ATTLIST object
  name CDATA #REQUIRED
>

<!ATTLIST page
  name ID #REQUIRED
  x CDATA #IMPLIED
  y CDATA #IMPLIED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  color CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  template CDATA #IMPLIED
>

<!ATTLIST line
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST vline
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST hline
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST box
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST rectangle
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  color CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST button
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  caption CDATA #IMPLIED
  captionx CDATA #IMPLIED
  captiony CDATA #IMPLIED
  captiondropx CDATA #IMPLIED
  captiondropy CDATA #IMPLIED
  template CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  fontfocusedcolor CDATA #IMPLIED
  fontdisabledcolor CDATA #IMPLIED
  fontpressedcolor CDATA #IMPLIED
  action CDATA #IMPLIED
  enabled (true | false | 0 | 1) "true"
  textalign (left | right | center | top | bottom) "center"
  autosize (true | false | 0 | 1) "false"
  wordwrap (true | false | 0 | 1) "false"
>

<!ATTLIST picture
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  image CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  template CDATA #IMPLIED
>

<!ATTLIST label
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  caption CDATA #IMPLIED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  textalign (left | right | center | top | bottom | topleft | topright | bottomleft | bottomright | vtop | vbottom | vcenter | hleft | hright | hcenter) "left"
  autosize (true | false | 0 | 1) "false"
  wordwrap (true | false | 0 | 1) "false"
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
>

<!ATTLIST clocklabel
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  textalign (left | right | center | top | bottom) "left"
  autosize (true | false | 0 | 1) "false"
  wordwrap (true | false | 0 | 1) "false"
  clockformat CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
>

<!ATTLIST listbox
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  selitembackground CDATA #IMPLIED
  selitembackgroundfocus CDATA #IMPLIED
  selitembackgroundcolor CDATA #IMPLIED
  selitembackgroundfocuscolor CDATA #IMPLIED
  selitembackgroundstyle (normal | tiled) "normal"
  selitemfontcolor CDATA #IMPLIED
  selitemfontcolorfocus CDATA #IMPLIED
  scrollbar CDATA #IMPLIED
  scrollbarbackground CDATA #IMPLIED
  scrollbarbackgroundstyle (normal | tiled | gradient | none) "normal"
  scrollbarknob CDATA #IMPLIED
  scrollbarwidth CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
  selitemborderx CDATA #IMPLIED
  selitembordery CDATA #IMPLIED
  itemborderx CDATA #IMPLIED
  itembordery CDATA #IMPLIED
  itemheight CDATA #IMPLIED
  wrap (true | false | 0 | 1) "false"
>

<!ATTLIST filebrowser
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  selitembackground CDATA #IMPLIED
  selitembackgroundfocus CDATA #IMPLIED
  selitembackgroundstyle (normal | tiled | gradient | none) "normal"
  selitemfontcolor CDATA #IMPLIED
  selitemfontcolorfocus CDATA #IMPLIED
  scrollbar CDATA #IMPLIED
  scrollbarbackground CDATA #IMPLIED
  scrollbarbackgroundstyle (normal | tiled | gradient | none) "normal"
  scrollbarknob CDATA #IMPLIED
  scrollbarwidth CDATA #IMPLIED
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  contentx CDATA #IMPLIED
  contenty CDATA #IMPLIED
  selitemborderx CDATA #IMPLIED
  selitembordery CDATA #IMPLIED
  itemborderx CDATA #IMPLIED
  itembordery CDATA #IMPLIED
  itemheight CDATA #IMPLIED
  rootpath CDATA #IMPLIED
>

<!ATTLIST webbrowser
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  location CDATA #IMPLIED
>

<!ATTLIST scrollbar
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  background CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  template CDATA #IMPLIED
  knob CDATA #IMPLIED
  knobfocus CDATA #IMPLIED
  reversed CDATA #IMPLIED
  maximum CDATA #IMPLIED
  minimum CDATA #IMPLIED
  pagestep CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
>

<!ATTLIST textfield
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  maxlength CDATA #IMPLIED
  validchars CDATA #IMPLIED
  font CDATA #IMPLIED
  fontsize CDATA #IMPLIED
  fontcolor CDATA #IMPLIED
  fontfocusedcolor CDATA #IMPLIED
  background CDATA #IMPLIED
  focusedbackground CDATA #IMPLIED
  pressedbackground CDATA #IMPLIED
  disabledbackground CDATA #IMPLIED
  backgroundstyle (normal | tiled | fill | gradient | none) "none"
  borderstyle ( normal | round | round_double | none ) "none"
  bordercolor CDATA #IMPLIED
  abordercolor CDATA #IMPLIED
  obordercolor CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  borderx CDATA #IMPLIED
  bordery CDATA #IMPLIED
  textalign CDATA #IMPLIED
  text CDATA #IMPLIED
>

<!ATTLIST togglebutton
  name CDATA #IMPLIED
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  template CDATA #IMPLIED
  normalimage CDATA #IMPLIED
  normalfocusimage CDATA #IMPLIED
  checkedimage CDATA #IMPLIED
  checkedfocusimage CDATA #IMPLIED
  color CDATA #IMPLIED
  focusedcolor CDATA #IMPLIED
  pressedcolor CDATA #IMPLIED
  disabledcolor CDATA #IMPLIED
  action CDATA #IMPLIED
  enabled (true | false | 0 | 1) "true"
  checked (true | false | 0 | 1) "false"
>

<!ATTLIST event
  type CDATA #REQUIRED
>

<!ATTLIST timer
  name CDATA #IMPLIED
  interval CDATA #REQUIRED
  enabled (true | false | 0 | 1) "false"
>

<!ATTLIST actionhandler
  action CDATA #REQUIRED
>

=== vseryakov/lmbox/modules/camera.xml
<?xml version="1.0"?>
<!DOCTYPE lmbox SYSTEM "lmbox.dtd">
<lmbox>

<page name="camerapage" background="background.jpg">
  <event name="OnGotFocus">
    camera_setup
    lmbox call cameralist setfocus
  </event>
  <event name="OnLostFocus">
    camera_stop
  </event>
  <event name="blue"> lmbox postevent cancel </event>
  <clocklabel x="20" y="10" width="300" height="20" template="clocklabel"></clocklabel>
  <label x="450" y="10" template="titlelabel">lmBox: Camera</label>
  <listbox name="cameralist" x="15" y="40" width="250" height="290" template="t_movielist">
    <event name="OnChoose">
      camera_set player [lmbox get cameralist selecteddata]
      lmbox setpage videopage
    </event>
    <event name="OnSelectionChange">
      camera_play player [lmbox get cameralist selecteddata] [lmbox get cameraview area]
      lmbox set status caption [lmbox get cameralist selecteddata]
    </event>
  </listbox>
  <picture name="cameraview" x="285" y="40" width="320" height="240" image="none.gif" borderstyle="normal" bordercolor="#e0e2e5" />
  <button x="20" y="360" caption="Zoom" template="t_graybutton" action="play">
    <event name="OnGotFocus">
      lmbox set status caption "Play stream fullscreen"
    </event>
    <event name="OnClick">
      camera_set player [lmbox get cameralist selecteddata]
      lmbox setpage videopage
    </event>
  </button>
  <button x="80" y="360" caption="Pause" template="t_graybutton" action="pause">
    <event name="OnGotFocus">
      lmbox set status caption "Pause camera stream"
    </event>
    <event name="OnClick">
      camera_pause
    </event>
  </button>
  <button x="140" y="360" caption="Details" template="t_graybutton">
    <event name="OnGotFocus">
      lmbox set status caption "Update/Delete live camera from the list"
    </event>
    <event name="OnClick">
      camera_edit
    </event>
  </button>
  <button x="200" y="360" caption="Mosaic" template="t_yellowbutton" action="yellow">
    <event name="OnGotFocus">
      lmbox set status caption "Watch all live cameras"
    </event>
    <event name="OnClick">
      lmbox setpage cameramosaicpage
    </event>
  </button>
  <button x="260" y="360" caption="Add" template="t_graybutton" >
    <event name="OnGotFocus">
      lmbox set status caption "Add new live camera"
    </event>
    <event name="OnClick">
      camera_add
    </event>
  </button>
  <button x="340" y="360" caption="Back" template="t_graybutton" action="cancel">
    <event name="OnGotFocus">
      lmbox set status caption "Go to main menu"
    </event>
    <event name="OnClick">
      lmbox setpage mainpage
    </event>
  </button>
  <label name="status" x="50" y="400" width="550" height="60" template="statuslabel" />
</page>

<page name="cameraeditpage" background="background.jpg">
  <event name="OnLostFocus">
    camera_stop
  </event>
  <event name="stop"> camera_stop </event>
  <event name="pause"> camera_pause </event>
  <event name="play"> camera_test </event>
  <clocklabel x="20" y="10" width="300" height="20" template="clocklabel"></clocklabel>
  <label name="cameracount" x="350" y="10" width="200" height="20" template="countlabel"></label>
  <label name="cameratitle" x="400" y="10" template="titlelabel">lmBox: Add New Camera</label>
  <label x="50" y="35" width="500" height="40" template="yellowlabel" textalign="center" fontsize="10" >
   Choose Video Device if your camera is directly attached or enter url of the remote device
  </label>
  <rectangle x="40" y="85" width="360" height="240" color="#e0e2e5" borderstyle="round" />
  <label x="50" y="100" width="150" height="20" template="infolabel">Camera Name:</label>
  <textfield name="camera_name" x="220" y="95" width="140" template="t_textfield">
    <event name="OnGotFocus">
      lmbox set status caption "Name of the camera, location for example like Living Room"
    </event>
  </textfield>
  <label x="50" y="130" width="150" height="20" template="infolabel">Video Device:</label>
  <listbox name="camera_device" x="220" y="125" width="140" height="20" template="t_listbox5" selitemfontcolor="#000000" >
    <event name="OnGotFocus">
      lmbox set status caption "Path to recorded V4L device, like /dev/video0"
    </event>
  </listbox>
  <label x="50" y="160" width="150" height="20" template="infolabel">Video Input:</label>
  <listbox name="camera_input" x="220" y="155" width="140" height="20" template="t_listbox5" selitemfontcolor="#000000" >
    <event name="OnGotFocus">
      lmbox set status caption "Video input source on the V4L device, like 0 or 2 or..."
    </event>
  </listbox>
  <label x="50" y="190" width="150" height="20" template="infolabel">Video System:</label>
  <listbox name="camera_norm" x="220" y="185" width="140" height="20" template="t_listbox5" selitemfontcolor="#000000" >
    <event name="OnGotFocus">
      lmbox set status caption "Type of TV Standard"
    </event>
  </listbox>
  <line x="40" y="245" width="359" height="1" color="#e0e2e5" />
  <label x="50" y="270" width="150" height="20" template="infolabel">Stream URL:</label>
  <textfield name="camera_url" x="220" y="265" width="140" template="t_textfield">
    <event name="OnGotFocus">
      lmbox set status caption "Url for network streaming cameras or any xine mrl, like file, fifo, http://host:port ..."
    </event>
  </textfield>
  <picture name="cameraview" x="410" y="120" width="170" height="150" image="none.gif" borderstyle="normal" bordercolor="#c5cd4a" />
  <button x="40" y="360" caption="Save" template="t_graybutton">
    <event name="OnGotFocus">
      lmbox set status caption "Save camera info"
    </event>
    <event name="OnClick">
      camera_save
    </event>
  </button>
  <button x="100" y="360" caption="Test" template="t_greenbutton" action="green">
    <event name="OnGotFocus">
      lmbox set status caption "Test camera, show streaming in the right rect"
    </event>
    <event name="OnClick">
      camera_test
    </event>
  </button>
  <button x="160" y="360" caption="Info" template="t_bluebutton" action="blue">
    <event name="OnGotFocus">
      lmbox set status caption "Video Device info"
    </event>
    <event name="OnClick">
      camera_info
    </event>
  </button>
  <button x="220" y="360" caption="Delete" template="t_graybutton">
    <event name="OnGotFocus">
      lmbox set status caption "Delete camera from the list"
    </event>
    <event name="OnClick">
      camera_delete
    </event>
  </button>
  <button x="280" y="360" caption="Back" template="t_graybutton" action="cancel">
    <event name="OnGotFocus">
      lmbox set status caption "Return to the list"
    </event>
    <event name="OnClick">
      lmbox setpage camerapage
    </event>
  </button>
  <label name="status" x="50" y="400" width="550" height="60" template="statuslabel" />
</page>

<page name="cameramosaicpage" background="background.jpg">
  <event name="OnGotFocus">
    camera_setup mosaic
  </event>
  <event name="OnLostFocus">
    camera_stop all
  </event>
  <event name="cancel"> lmbox setpage camerapage </event>
  <clocklabel x="20" y="10" width="300" height="20" template="clocklabel"></clocklabel>
  <label name="cameracount" x="350" y="10" width="200" height="20" template="countlabel"></label>
  <label name="cameratitle" x="450" y="10" template="titlelabel">lmBox: Camera Mosaic</label>
  <button name="cameraview1" x="135" y="30" width="206" height="175" template="t_button" textalign="bottom" >
    <event name="OnGotFocus">
      lmbox set status caption [lmbox get this data]
    </event>
    <event name="OnClick">
      camera_set player [lmbox get this data]
      lmbox setpage videopage
    </event>
  </button>
  <button name="cameraview2" x="360" y="30" width="206" height="175" template="t_button" textalign="bottom" >
    <event name="OnGotFocus">
      lmbox set status caption [lmbox get this data]
    </event>
    <event name="OnClick">
      camera_set player [lmbox get this data]
      lmbox setpage videopage
    </event>
  </button>
  <button name="cameraview3" x="135" y="220" width="206" height="175" template="t_button" textalign="bottom" >
    <event name="OnGotFocus">
      lmbox set status caption [lmbox get this data]
    </event>
    <event name="OnClick">
      camera_set player [lmbox get this data]
      lmbox setpage videopage
    </event>
  </button>
  <button name="cameraview4" x="360" y="220" width="206" height="175" template="t_button" textalign="bottom" >
    <event name="OnGotFocus">
      lmbox set status caption [lmbox get this data]
    </event>
    <event name="OnClick">
      camera_set player [lmbox get this data]
      lmbox setpage videopage
    </event>
  </button>
  <label name="status" x="50" y="400" width="550" height="60" template="statuslabel" />
</page>

</lmbox>

=== vseryakov/lmbox/modules/fmtuner.xml
<?xml version="1.0"?>
<!DOCTYPE lmbox SYSTEM "lmbox.dtd">
<lmbox>

<page name="fmtunerpage" background="background.jpg">
   <clocklabel x="20" y="15"  width="300" height="20" template="clocklabel" />
   <rectangle x="100" y="80" width="450" height="105" />
   <label x="400" y="10" template="titlelabel">lmBox: Radio Tuner</label>
   <label x="150" y="85" name="fmtunerfreq" template="titlelabel" fontsize="50" />
   <label x="500" y="85" name="fmtunerpreset" template="titlelabel" fontcolor="#FFFFFF" />
   <label x="500" y="150" name="fmtunerstereo" template="titlelabel" fontsize="12" />
   <button x="100" y="230" caption="Play" template="t_button2" action="play">
     <event name="OnGotFocus">
       lmbox set status caption "Play radio"
     </event>
     <event name="OnClick">
       fmtuner_play
     </event>
   </button>
   <button x="220" y="230" caption="Stop" template="t_button2" action="stop">
     <event name="OnGotFocus">
       lmbox set status caption "Stop radio"
     </event>
     <event name="OnClick">
       fmtuner_stop
     </event>
   </button>
   <button x="340" y="230" caption="Next" template="t_button2" action="nexttrack">
     <event name="OnGotFocus">
       lmbox set status caption "Increase radio frequency"
     </event>
     <event name="OnClick">
       fmtuner_next 0.10
     </event>
   </button>
   <button x="460" y="230" caption="Prev" template="t_button2" action="prevtrack">
     <event name="OnGotFocus">
       lmbox set status caption "Decrease radio frequency"
     </event>
     <event name="OnClick">
       fmtuner_next -0.10
     </event>
   </button>
   <button x="100" y="280" caption="FF" template="t_button2">
     <event name="OnGotFocus">
       lmbox set status caption "Seek for next stable radio frequency"
     </event>
     <event name="OnClick">
       fmtuner_seek 1
     </event>
   </button>
   <button x="220" y="280" caption="REW" template="t_button2">
     <event name="OnGotFocus">
       lmbox set status caption "Go back"
     </event>
     <event name="OnClick">
       fmtuner_seek -1
     </event>
   </button>
   <button x="340" y="280" caption="Save" template="t_button2">
     <event name="OnGotFocus">
       lmbox set status caption "Save frequency into presets, when pressed go and choose SetN button to save"
     </event>
     <event name="OnClick">
       fmtuner_save
     </event>
   </button>
   <button x="460" y="280" caption="Back" template="t_button2" action="cancel">
     <event name="OnGotFocus">
       lmbox set status caption "Go back"
     </event>
     <event name="OnClick">
       lmbox setpage mainpage
     </event>
   </button>
   <button x="100" y="330" caption="Set 1" template="t_button2" action="number1">
     <event name="OnGotFocus">
       lmbox set status caption "Play/Save preset station"
     </event>
     <event name="OnClick">
       fmtuner_preset 1
     </event>
   </button>
   <button x="220" y="330" caption="Set 2" template="t_button2" action="number2">
     <event name="OnGotFocus">
       lmbox set status caption "Play/Save preset station"
     </event>
     <event name="OnClick">
       fmtuner_preset 2
     </event>
   </button>
   <button x="340" y="330" caption="Set 3" template="t_button2" action="number3">
     <event name="OnGotFocus">
       lmbox set status caption "Play/Save preset station"
     </event>
     <event name="OnClick">
       fmtuner_preset 3
     </event>
   </button>
   <button x="460" y="330" caption="Set 4" template="t_button2" action="number4">
     <event name="OnGotFocus">
       lmbox set status caption "Play/Save preset station"
     </event>
     <event name="OnClick">
       fmtuner_preset 4
     </event>
   </button>
   <button x="100" y="380" caption="Set 5" template="t_button2" action="number5">
     <event name="OnGotFocus">
       lmbox set status caption "Play/Save preset station"
     </event>
     <event name="OnClick">
       fmtuner_preset 5
     </event>
   </button>
   <button x="220" y="380" caption="Set 6" template="t_button2" action="number6">
     <event name="OnGotFocus">
       lmbox set status caption "Play/Save preset station"
     </event>
     <event name="OnClick">
       fmtuner_preset 6
     </event>
   </button>
   <button x="340" y="380" caption="Set 7" template="t_button2" action="number7">
     <event name="OnGotFocus">
       lmbox set status caption "Play/Save preset station"
     </event>
     <event name="OnClick">
       fmtuner_preset 7
     </event>
   </button>
   <button x="460" y="380" caption="Set 8" template="t_button2" action="number8">
     <event name="OnGotFocus">
       lmbox set status caption "Play/Save preset station"
     </event>
     <event name="OnClick">
       fmtuner_preset 8
     </event>
   </button>
   <label name="status" x="10" y="410" width="580" height="30" template="statuslabel"></label>
</page>

</lmbox>
